###
# #%L
# Spawn Local JDK
# %%
# Copyright (C) 2026 Workday, Inc.
# %%
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#      http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# #L%
###
#
# Defines mappings to JDK installation paths (aka: Java Homes)
#
# Paths must be absolute. They may contain globs, allowing the definition of patterns for paths.
# For example, the following mapping defines JDK paths on macOS for zulu
#
#   macos-zulu = /Library/Java/JavaVirtualMachines/zulu-*.jdk/Contents/Home
#

macos-zulu = /Library/Java/JavaVirtualMachines/zulu-*.jdk/Contents/Home
macos-java = /Library/Java/JavaVirtualMachines/jdk*.jdk/Contents/Home
standard-linux-java = /usr/lib/jvm/java-*
usr-local-jdk = /usr/local/*jdk*
usr-local-java = /usr/local/*java*
